from enum import StrEnum
class MessageType(StrEnum):
    REQUEST='REQUEST'; RESPONSE='RESPONSE'; EVENT='EVENT'; ERROR='ERROR'; CANCEL='CANCEL'; HEARTBEAT='HEARTBEAT'; CAPABILITY_ANNOUNCEMENT='CAPABILITY_ANNOUNCEMENT'
class Sensitivity(StrEnum):
    PUBLIC='PUBLIC'; INTERNAL='INTERNAL'; CONFIDENTIAL='CONFIDENTIAL'; RESTRICTED='RESTRICTED'
